import { Controller, Get, Req, Res } from '@nestjs/common';

/**
 * CSRF Token Controller
 * Provides CSRF token endpoints for client-side protection
 */
@Controller('security')
export class CsrfController {
  /**
   * Get CSRF token for the current session
   * This endpoint should be called on app initialization
   *
   * @returns CSRF token
   */
  @Get('csrf-token')
  getCsrfToken(@Req() req: any, @Res() res: any) {
    // Token is automatically generated by csurf middleware
    const token = req.csrfToken();

    return res.json({
      csrfToken: token,
      message: 'CSRF token generated successfully',
    });
  }
}
