import { Controller, Get, Req, Res, Logger } from '@nestjs/common';

/**
 * CSRF Token Controller
 * Provides CSRF token endpoints for client-side protection
 *
 * Note: CSRF protection is currently disabled in development.
 * This endpoint returns a mock token for compatibility.
 */
@Controller('security')
export class CsrfController {
  private readonly logger = new Logger(CsrfController.name);

  /**
   * Get CSRF token for the current session
   * This endpoint should be called on app initialization
   *
   * @returns CSRF token
   */
  @Get('csrf-token')
  getCsrfToken(@Req() req: any, @Res() res: any) {
    // Check if CSRF middleware is enabled (req.csrfToken will be a function)
    if (typeof req.csrfToken === 'function') {
      // Token is automatically generated by csurf middleware
      const token = req.csrfToken();
      return res.json({
        csrfToken: token,
        message: 'CSRF token generated successfully',
      });
    }

    // CSRF is disabled - return a mock token for development
    this.logger.warn('CSRF protection is disabled. Returning mock token.');
    return res.json({
      csrfToken: 'csrf-disabled-development-only',
      message: 'CSRF protection disabled (development mode)',
      warning: 'CSRF protection should be enabled in production',
    });
  }
}
