import { Counter, Histogram, Gauge } from 'prom-client';
export declare class MetricsService {
    private readonly serviceName;
    private readonly httpRequestsTotal;
    private readonly httpRequestDuration;
    private readonly httpResponseSize;
    private readonly httpRequestSize;
    private readonly dbQueryDuration;
    private readonly dbConnectionsActive;
    private readonly dbQueriesTotal;
    private readonly dbErrorsTotal;
    private readonly queueJobsTotal;
    private readonly queueJobDuration;
    private readonly queueJobsActive;
    private readonly queueJobsWaiting;
    private readonly queueJobsFailedTotal;
    private readonly agentsActiveCount;
    private readonly agentsExecutionsTotal;
    private readonly agentsExecutionDuration;
    private readonly agentsErrorsTotal;
    private readonly tasksCreatedTotal;
    private readonly tasksCompletedTotal;
    private readonly tasksFailedTotal;
    private readonly tasksPendingCount;
    private readonly workflowExecutionsTotal;
    private readonly workflowExecutionDuration;
    private readonly workflowErrorsTotal;
    private readonly apiRateLimitExceededTotal;
    private readonly memoryHeapUsedBytes;
    private readonly cpuUsagePercentage;
    private readonly cacheHitsTotal;
    private readonly cacheMissesTotal;
    constructor(serviceName: string, httpRequestsTotal: Counter<string>, httpRequestDuration: Histogram<string>, httpResponseSize: Histogram<string>, httpRequestSize: Histogram<string>, dbQueryDuration: Histogram<string>, dbConnectionsActive: Gauge<string>, dbQueriesTotal: Counter<string>, dbErrorsTotal: Counter<string>, queueJobsTotal: Counter<string>, queueJobDuration: Histogram<string>, queueJobsActive: Gauge<string>, queueJobsWaiting: Gauge<string>, queueJobsFailedTotal: Counter<string>, agentsActiveCount: Gauge<string>, agentsExecutionsTotal: Counter<string>, agentsExecutionDuration: Histogram<string>, agentsErrorsTotal: Counter<string>, tasksCreatedTotal: Counter<string>, tasksCompletedTotal: Counter<string>, tasksFailedTotal: Counter<string>, tasksPendingCount: Gauge<string>, workflowExecutionsTotal: Counter<string>, workflowExecutionDuration: Histogram<string>, workflowErrorsTotal: Counter<string>, apiRateLimitExceededTotal: Counter<string>, memoryHeapUsedBytes: Gauge<string>, cpuUsagePercentage: Gauge<string>, cacheHitsTotal: Counter<string>, cacheMissesTotal: Counter<string>);
    recordHttpRequest(method: string, path: string, statusCode: number, duration: number, requestSize?: number, responseSize?: number): void;
    recordDbQuery(operation: string, table: string, duration: number): void;
    recordDbError(operation: string, table: string, errorType: string): void;
    setDbConnections(activeConnections: number): void;
    recordQueueJob(queueName: string, jobType: string, status: 'completed' | 'failed', duration?: number): void;
    setQueueJobsActive(queueName: string, count: number): void;
    setQueueJobsWaiting(queueName: string, count: number): void;
    setActiveAgents(count: number): void;
    recordAgentExecution(agentType: string, status: 'success' | 'error', duration: number): void;
    recordTaskCreated(taskType: string): void;
    recordTaskCompleted(taskType: string): void;
    recordTaskFailed(taskType: string, errorType: string): void;
    setTasksPending(count: number): void;
    recordWorkflowExecution(workflowType: string, status: 'success' | 'error', duration: number): void;
    recordRateLimitExceeded(endpoint: string, userId?: string): void;
    recordCacheHit(cacheKey: string): void;
    recordCacheMiss(cacheKey: string): void;
    private normalizeHttpPath;
    private normalizeCacheKey;
    private startProcessMetricsCollection;
}
export declare const metricsProviders: import("@nestjs/common").Provider[];
