export * from './proxy.module';
export * from './auth-proxy.controller';
export * from './crm-proxy.controller';
export * from './campaigns-proxy.controller';
export * from './content-proxy.controller';
export * from './agents-proxy.controller';
export * from './tasks-proxy.controller';
export * from './automations-proxy.controller';
export * from './reports-proxy.controller';
