import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { TrendingUp, CheckCircle2, AlertCircle, FileText, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';

export default function AIReportCard({ report, clientId }) {
  if (!report) return null;

  const getSuccessColor = (rate) => {
    if (rate >= 80) return 'text-green-400';
    if (rate >= 60) return 'text-yellow-400';
    return 'text-red-400';
  };

  const handleDownload = () => {
    const reportText = `
CLIENT PROGRESS REPORT
Generated: ${new Date(report.generated_at).toLocaleString()}

PERFORMANCE SUMMARY
${report.performance_summary}

KEY METRICS
- Campaigns: ${report.metrics.total_campaigns} (${report.metrics.active_campaigns} active)
- Completed Tasks: ${report.metrics.completed_tasks}
- Failed Tasks: ${report.metrics.failed_tasks}
- Total Leads: ${report.metrics.total_leads}
- Qualified Leads: ${report.metrics.qualified_leads}
- Success Rate: ${report.metrics.success_rate}%

KEY WINS
${report.key_wins.map((win, i) => `${i + 1}. ${win}`).join('\n')}

AREAS FOR IMPROVEMENT
${report.areas_for_improvement.map((area, i) => `${i + 1}. ${area}`).join('\n')}

RECOMMENDED FOCUS
${report.recommended_focus.map((focus, i) => `${i + 1}. ${focus}`).join('\n')}
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `client-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <Card className="p-6" style={{ 
      backgroundColor: 'var(--bg-card)', 
      border: '1px solid var(--border-subtle)' 
    }}>
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center space-x-2">
          <FileText className="w-5 h-5 text-purple-400" />
          <div>
            <h3 className="font-semibold" style={{ color: 'var(--text-primary)' }}>
              Progress Report
            </h3>
            <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
              Auto-generated by AI
            </p>
          </div>
        </div>
        <Button 
          variant="ghost" 
          size="sm"
          onClick={handleDownload}
          style={{ color: 'var(--text-secondary)' }}
        >
          <Download className="w-3 h-3 mr-2" />
          Export
        </Button>
      </div>

      {/* Metrics Overview */}
      <div className="grid grid-cols-3 gap-3 mb-4 p-4 rounded-lg" style={{ backgroundColor: 'var(--bg-surface)' }}>
        <div className="text-center">
          <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            {report.metrics.active_campaigns}
          </div>
          <div className="text-xs" style={{ color: 'var(--text-muted)' }}>Active Campaigns</div>
        </div>
        <div className="text-center">
          <div className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
            {report.metrics.completed_tasks}
          </div>
          <div className="text-xs" style={{ color: 'var(--text-muted)' }}>Completed Tasks</div>
        </div>
        <div className="text-center">
          <div className={`text-2xl font-bold ${getSuccessColor(report.metrics.success_rate)}`}>
            {report.metrics.success_rate}%
          </div>
          <div className="text-xs" style={{ color: 'var(--text-muted)' }}>Success Rate</div>
        </div>
      </div>

      {/* Performance Summary */}
      <div className="mb-4">
        <h4 className="text-sm font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>
          Performance Summary
        </h4>
        <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
          {report.performance_summary}
        </p>
      </div>

      {/* Key Wins */}
      {report.key_wins?.length > 0 && (
        <div className="mb-4">
          <div className="flex items-center space-x-2 mb-2">
            <CheckCircle2 className="w-4 h-4 text-green-400" />
            <h4 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
              Key Wins
            </h4>
          </div>
          <ul className="space-y-1">
            {report.key_wins.map((win, idx) => (
              <motion.li
                key={idx}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: idx * 0.1 }}
                className="text-sm flex items-start space-x-2"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span className="text-green-400 mt-1">•</span>
                <span>{win}</span>
              </motion.li>
            ))}
          </ul>
        </div>
      )}

      {/* Areas for Improvement */}
      {report.areas_for_improvement?.length > 0 && (
        <div className="mb-4">
          <div className="flex items-center space-x-2 mb-2">
            <AlertCircle className="w-4 h-4 text-yellow-400" />
            <h4 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
              Areas for Improvement
            </h4>
          </div>
          <ul className="space-y-1">
            {report.areas_for_improvement.map((area, idx) => (
              <motion.li
                key={idx}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: idx * 0.1 }}
                className="text-sm flex items-start space-x-2"
                style={{ color: 'var(--text-secondary)' }}
              >
                <span className="text-yellow-400 mt-1">•</span>
                <span>{area}</span>
              </motion.li>
            ))}
          </ul>
        </div>
      )}

      {/* Recommended Focus */}
      {report.recommended_focus?.length > 0 && (
        <div>
          <div className="flex items-center space-x-2 mb-2">
            <TrendingUp className="w-4 h-4 text-blue-400" />
            <h4 className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
              Recommended Focus Areas
            </h4>
          </div>
          <div className="flex flex-wrap gap-2">
            {report.recommended_focus.map((focus, idx) => (
              <Badge 
                key={idx}
                variant="outline" 
                className="text-xs"
                style={{ borderColor: 'var(--border-subtle)', color: 'var(--text-secondary)' }}
              >
                {focus}
              </Badge>
            ))}
          </div>
        </div>
      )}
    </Card>
  );
}